version: 1.1.0.{build}

skip_tags: true

assembly_info:
  patch: true
  file: 'src\\VersionInfo.cs'
  assembly_version: '1.1.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{commitId}'

configuration: Release

before_build:
  - nuget restore 'src\NCeption.sln'
  - nuget restore 'build\packages.config' -ExcludeVersion -OutPutDirectory 'tools\packages'

build:
  parallel: true
  project: build\RestoreAndBuild.proj

test:
  categories:
    except:
      - WebTests
      - DatabaseTests

deploy:
  provider: NuGet
  api_key:
    secure: UWLHsXH6B9+FIAZ4HCbSnvKBAi1LHvmA3JLtLfjUccKRIUwS1VgutW5j9UkizRBn
  artifact: '**\NCep*.nupkg'