version_major: 1.1
version_assembly: {version_major}.0.0
version: {version_major}.0.{build}

assembly_info:
	patch: true
	file: VersionInfo.cs
	assembly_version: "{version_major}.0.0"
	assembly_file_version: "{version}"
	assembly_informational_version: "NCeption {version_major}"

build:
	project: NCeption.sln
	publish_nuget: true

deploy:
	provider: NuGet
	api_key:
		secure: UWLHsXH6B9+FIAZ4HCbSnvKBAi1LHvmA3JLtLfjUccKRIUwS1VgutW5j9UkizRBn
	artifact: '**\NCep*.nupkg'