version: 1.1.0.{build}

skip_tags: true

assembly_info:
	patch: true
	file: VersionInfo.cs
	assembly_version: 1.1.0.0
	assembly_file_version: "{version}"
	assembly_informational_version: "{commitId}"

build:
	parallel: true
	project: NCeption.sln
	publish_nuget: true

deploy:
	provider: NuGet
	api_key:
		secure: UWLHsXH6B9+FIAZ4HCbSnvKBAi1LHvmA3JLtLfjUccKRIUwS1VgutW5j9UkizRBn
	artifact: '**\NCep*.nupkg'